name: Cypress browser tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  browser-test:
    name: Cypress browser tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14, 16, 18 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          install-command: yarn install --immutable
          build: yarn workspace storybook-addon-performance run build
          working-directory: packages/storybook-addon-performance
          start: yarn workspaces foreach -piv run storybook:dev
          wait-on: 'http://localhost:9003, http://localhost:9004, http://localhost:9005'
          wait-on-timeout: 180
      # Upload the videos and screenshots
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        # We want to upload the recording even if the last step failed
        # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
        if: always()
        with:
          name: cypress-videos
          path: /packages/storybook-addon-performance/cypress/videos
